export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const EMPLOYEES_REPOSITORY = 'EMPLOYEES_REPOSITORY';
export const DEPARTMENTS_REPOSITORY = 'DEPARTMENTS_REPOSITORY';
export const POSITIONS_REPOSITORY = 'POSITIONS_REPOSITORY';
export const DATA_SOURCE = 'DATA_SOURCE';
